# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Windows_Main.ui'
#
# Created: Tue Jan 24 03:15:16 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Windows_Main(object):
    def setupUi(self, Windows_Main):
        Windows_Main.setObjectName(_fromUtf8("Windows_Main"))
        Windows_Main.resize(752, 550)
        Windows_Main.setWindowTitle(QtGui.QApplication.translate("Windows_Main", "IMTAphyViewer 0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(Windows_Main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        Windows_Main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Windows_Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("Windows_Main", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        Windows_Main.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Windows_Main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Windows_Main.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(Windows_Main)
        self.actionQuit.setText(QtGui.QApplication.translate("Windows_Main", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("Windows_Main", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAboutQt = QtGui.QAction(Windows_Main)
        self.actionAboutQt.setText(QtGui.QApplication.translate("Windows_Main", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQt.setObjectName(_fromUtf8("actionAboutQt"))
        self.actionAboutWrowser = QtGui.QAction(Windows_Main)
        self.actionAboutWrowser.setText(QtGui.QApplication.translate("Windows_Main", "About Wrowser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutWrowser.setObjectName(_fromUtf8("actionAboutWrowser"))
        self.actionOpenDatabase = QtGui.QAction(Windows_Main)
        self.actionOpenDatabase.setText(QtGui.QApplication.translate("Windows_Main", "Open S&QLObject Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenDatabase.setObjectName(_fromUtf8("actionOpenDatabase"))
        self.actionOpenDSV = QtGui.QAction(Windows_Main)
        self.actionOpenDSV.setText(QtGui.QApplication.translate("Windows_Main", "Open DS&V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenDSV.setIconText(QtGui.QApplication.translate("Windows_Main", "Open DSV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenDSV.setObjectName(_fromUtf8("actionOpenDSV"))
        self.actionOpenPythonCampaign = QtGui.QAction(Windows_Main)
        self.actionOpenPythonCampaign.setText(QtGui.QApplication.translate("Windows_Main", "Open &Python Campaign", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenPythonCampaign.setObjectName(_fromUtf8("actionOpenPythonCampaign"))
        self.actionOpenDirectory = QtGui.QAction(Windows_Main)
        self.actionOpenDirectory.setText(QtGui.QApplication.translate("Windows_Main", "Open &Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenDirectory.setObjectName(_fromUtf8("actionOpenDirectory"))
        self.actionCloseFigure = QtGui.QAction(Windows_Main)
        self.actionCloseFigure.setText(QtGui.QApplication.translate("Windows_Main", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloseFigure.setObjectName(_fromUtf8("actionCloseFigure"))
        self.actionCloseDataSource = QtGui.QAction(Windows_Main)
        self.actionCloseDataSource.setEnabled(False)
        self.actionCloseDataSource.setText(QtGui.QApplication.translate("Windows_Main", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloseDataSource.setObjectName(_fromUtf8("actionCloseDataSource"))
        self.actionNewLogEval = QtGui.QAction(Windows_Main)
        self.actionNewLogEval.setText(QtGui.QApplication.translate("Windows_Main", "LogEval", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewLogEval.setObjectName(_fromUtf8("actionNewLogEval"))
        self.actionNewTimeSeries = QtGui.QAction(Windows_Main)
        self.actionNewTimeSeries.setText(QtGui.QApplication.translate("Windows_Main", "TimeSeries", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewTimeSeries.setObjectName(_fromUtf8("actionNewTimeSeries"))
        self.actionNewLRE = QtGui.QAction(Windows_Main)
        self.actionNewLRE.setText(QtGui.QApplication.translate("Windows_Main", "(D)LRE", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewLRE.setObjectName(_fromUtf8("actionNewLRE"))
        self.actionNewBatchMeans = QtGui.QAction(Windows_Main)
        self.actionNewBatchMeans.setText(QtGui.QApplication.translate("Windows_Main", "BatchMeans", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewBatchMeans.setObjectName(_fromUtf8("actionNewBatchMeans"))
        self.actionNewTable = QtGui.QAction(Windows_Main)
        self.actionNewTable.setText(QtGui.QApplication.translate("Windows_Main", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewTable.setObjectName(_fromUtf8("actionNewTable"))
        self.actionNewXDF = QtGui.QAction(Windows_Main)
        self.actionNewXDF.setText(QtGui.QApplication.translate("Windows_Main", "PDF/CDF/CCDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewXDF.setObjectName(_fromUtf8("actionNewXDF"))
        self.actionNewParameter = QtGui.QAction(Windows_Main)
        self.actionNewParameter.setText(QtGui.QApplication.translate("Windows_Main", "Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewParameter.setObjectName(_fromUtf8("actionNewParameter"))
        self.actionConfigure = QtGui.QAction(Windows_Main)
        self.actionConfigure.setText(QtGui.QApplication.translate("Windows_Main", "C&onfigure...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionOpenCampaignDatabase = QtGui.QAction(Windows_Main)
        self.actionOpenCampaignDatabase.setText(QtGui.QApplication.translate("Windows_Main", "Open &Campaign Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenCampaignDatabase.setObjectName(_fromUtf8("actionOpenCampaignDatabase"))
        self.actionRefresh = QtGui.QAction(Windows_Main)
        self.actionRefresh.setText(QtGui.QApplication.translate("Windows_Main", "&Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionView_Scenario = QtGui.QAction(Windows_Main)
        self.actionView_Scenario.setText(QtGui.QApplication.translate("Windows_Main", "View &Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Scenario.setObjectName(_fromUtf8("actionView_Scenario"))
        self.actionPreferences = QtGui.QAction(Windows_Main)
        self.actionPreferences.setText(QtGui.QApplication.translate("Windows_Main", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionView_CouchDB_Trace = QtGui.QAction(Windows_Main)
        self.actionView_CouchDB_Trace.setText(QtGui.QApplication.translate("Windows_Main", "View CouchDB Trace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_CouchDB_Trace.setObjectName(_fromUtf8("actionView_CouchDB_Trace"))
        self.menuFile.addAction(self.actionCloseDataSource)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionView_Scenario)
        self.menuFile.addAction(self.actionView_CouchDB_Trace)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Windows_Main)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), Windows_Main.close)
        QtCore.QMetaObject.connectSlotsByName(Windows_Main)

    def retranslateUi(self, Windows_Main):
        pass

import viewer_rc
